from app.schemas import ma
from marshmallow import fields


# Define the Comment Schema
class CommentSchema(ma.Schema):
    comment_id = fields.Integer(required=False)  # id is autogenerated
    content = fields.String(required=True)
    post_id = fields.Integer(required=True)
    user_id = fields.Integer(required=False)  # user_id is extracted from the token and not required in the request body


# Create instances of the schema
comment_schema = CommentSchema()
comments_schema = CommentSchema(many=True)