from app.schemas import ma
from marshmallow import fields


# Define the Customer Schema
class PostSchema(ma.Schema):
    post_id = fields.Integer(required=False) # id is autogenerated
    title = fields.String(required=True)
    body = fields.String(required=True)
    user_id = fields.Integer(required=False) 


# Create instances of the schema
post_schema = PostSchema()
posts_schema = PostSchema(many=True)