"""Add roles

Revision ID: 922eebbca3d9
Revises: 42a71754fce4
Create Date: 2024-07-09 01:50:22.601518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922eebbca3d9'
down_revision = '42a71754fce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
